Repository MangaSeed/serverless-demo-client-redux-materialui, pull requests merged in 2019-11, with the labels that each got.

#2 refactor: change codebase into material-ui
  CHANGELOG.md
  package-lock.json
  package.json
  public/index.html
  src/App.css
  src/App.js
  src/Routes.js
  src/components/BillingForm.css
  src/components/BillingForm.js
  src/components/LoaderButton.js
  src/components/Navigation/Navigation.js
  src/components/Navigation/Navigation.style.js
  src/containers/Home.css
  src/containers/Home.js
  src/containers/Home/Home.js
  src/containers/Home/Home.style.js
  src/containers/Login.css
  src/containers/Login.js
  src/containers/Login/Login.js
  src/containers/NewNote.css
  src/containers/NewNote.js
  src/containers/NewNote/NewNote.js
  src/containers/NewNote/NewNote.style.js
  src/containers/NotFound.css
  src/containers/NotFound.js
  src/containers/NotFound/NotFound.js
  src/containers/Note/Notes.js
  src/containers/Note/Notes.style.js
  src/containers/Notes.css
  src/containers/Notes.js
  src/containers/Settings.css
  src/containers/Settings/Settings.js
  src/containers/Signup/Signup.css
  src/containers/Signup/Signup.js
  src/index.css
  src/index.js
Labels: enhancement, refactor

#8 add `REACT_APP_VERSION` to header
  .env.production
  package-lock.json
  package.json
  src/components/Navigation/Navigation.style.ts
  src/components/Navigation/Navigation.tsx
Labels: enhancement

#7 feat: redux boilerplate
  package-lock.json
  package.json
  src/index.tsx
  src/store/index.ts
  src/store/reducers/index.ts
  src/store/reducers/note.ts
  src/store/sagas/index.ts
Labels: enhancement

#5 feat: file service
  src/services/file.ts
Labels: enhancement

#11 chore: prettier config
  .prettierrc
  package-lock.json
  package.json
  tslint.json
Labels: chore
